app:
  name: default_app
  env: default


market-config:
  markets:
    btc-inr:
      base_currency_decimal_places: 8
      quote_currency_decimal_places: 2
    ltc-inr:
      base_currency_decimal_places: 8
      quote_currency_decimal_places: 2
    eth-inr:
      base_currency_decimal_places: 8
      quote_currency_decimal_places: 2

type-config:
  types:
    limit:
      - post_only
      - time_in_force

action-config:
  actions:
    - ORDER_PLACING
    - ORDER_CANCELLATION
    - ORDER_REPLACE


websocket-publish-services:
  source:
    trades:
      dest_topic: ${TRADES_DEST_TOPIC}
      event_name: Trade
      type: Public
    open_trade_buckets:
      dest_topic: ${ORDER_BOOK_DEST_TOPIC}
      event_name: OrderBook
      type: Public
